name: Deploy docs
on:
  push:
    branches:
      - main

jobs:
  clickup-headsup:
    name: ClickUp heads-up
    runs-on: ubuntu-latest
    steps:
      - name: Call ClickUp api
        uses: smplrspace/clickup-chat-action@v1
        with:
          workspace-id: 3887534
          channel-id: 3pmde-14775 # dev
          message: |
            🟣 Started: ${{ github.workflow}}
        env:
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_BEEBOP_API_KEY }}

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for Cloudflare Pages build
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_PAGES  }}
          accountId: "4955c8c28610ecabc384d84a20458a53"
          project: "docs"
          # write deployment status to github
          githubToken: ${{ secrets.PRIVATE_ACCESS_TOKEN_DEPLOYMENTS }}

  clickup-notification:
    name: ClickUp notification
    if: always()
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: Call ClickUp api
        uses: smplrspace/clickup-chat-action@v1
        with:
          workspace-id: 3887534
          channel-id: 3pmde-14775 # dev
          status-update: true
          status: ${{ steps.check.outputs.status }}
        env:
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_BEEBOP_API_KEY }}
